const THEMES=[
{id:'hardware',icon:'🖥️',title:'Composants & périphériques'},
{id:'connectivity',icon:'🔌',title:'Connectivité'},
{id:'units',icon:'📦',title:'Unités de mesure'},
{id:'internal',icon:'🧩',title:'Composants internes'},
{id:'systems',icon:'⚙️',title:'Systèmes & traitement'},
{id:'os',icon:'🪟',title:"Systèmes d’exploitation"},
{id:'network',icon:'🌐',title:'Réseaux informatiques'}];
const E=[
{id:1,t:'hardware',title:"L’ordinateur",desc:'Découvrir les principaux éléments d’un poste.',visual:'assets/computer.svg',concept:'Un poste informatique réunit des périphériques d’entrée, de sortie, de stockage et une unité de traitement.',type:'match',pairs:[['Écran','Affiche les informations'],['Unité centrale','Traite les données'],['Clavier','Permet de saisir du texte'],['Souris','Permet de pointer et sélectionner'],['Haut-parleur','Restitue le son']]},
{id:2,t:'hardware',title:'Périphériques externes',desc:'Identifier des périphériques courants.',visual:'assets/peripherals.svg',concept:'Les périphériques sont des équipements connectés à l’ordinateur pour saisir, afficher, stocker ou restituer des informations.',type:'mcq',questions:[{q:'Quel périphérique permet de numériser une feuille papier ?',o:['Scanner','Écran','Clavier','Haut-parleur'],a:0},{q:'Quel périphérique capture une vidéo ?',o:['Webcam','Imprimante','Routeur','SSD'],a:0},{q:'Quel équipement produit une copie papier ?',o:['Imprimante','Souris','Microphone','Switch'],a:0}]},
{id:3,t:'hardware',title:'Fonctions des périphériques',desc:'Relier chaque périphérique à sa fonction.',visual:'assets/peripherals.svg',concept:'On reconnaît un périphérique par le service qu’il rend : saisie, affichage, son, impression ou capture.',type:'match',pairs:[['Microphone','Capturer le son'],['Webcam','Capturer image et vidéo'],['Imprimante','Imprimer sur papier'],['Écran','Afficher les résultats'],['Scanner','Numériser un document']]},
{id:4,t:'hardware',title:'Entrée et sortie',desc:'Classer les périphériques selon le sens des données.',visual:'assets/peripherals.svg',concept:'Un périphérique d’entrée envoie des données vers l’ordinateur ; un périphérique de sortie restitue un résultat.',type:'classify',cats:['Entrée','Sortie'],items:[['Clavier','Entrée'],['Souris','Entrée'],['Microphone','Entrée'],['Écran','Sortie'],['Imprimante','Sortie'],['Haut-parleur','Sortie']]},
{id:5,t:'hardware',title:'Classification complète',desc:'Distinguer entrée, sortie, mixte et stockage.',visual:'assets/computer.svg',concept:'Certains équipements sont mixtes (entrée/sortie) et d’autres servent surtout au stockage durable.',type:'classify',cats:['Entrée','Sortie','Entrée/Sortie','Stockage'],items:[['Écran tactile','Entrée/Sortie'],['Clé USB','Stockage'],['Scanner','Entrée'],['Projecteur','Sortie'],['Disque SSD','Stockage'],['Casque-micro','Entrée/Sortie']]},
{id:6,t:'connectivity',title:'Périphériques et connecteurs',desc:'Associer l’usage au connecteur.',visual:'assets/ports.svg',concept:'Chaque port a une forme et un usage. USB est polyvalent, HDMI sert souvent à l’affichage numérique, RJ45 au réseau.',type:'match',pairs:[['Clavier filaire','USB'],['Écran numérique','HDMI'],['Réseau Ethernet','RJ45'],['Casque audio','Jack audio']]},
{id:7,t:'connectivity',title:'Connecteurs et ports',desc:'Choisir le bon port.',visual:'assets/ports.svg',concept:'Identifier un connecteur permet de brancher correctement les périphériques sans forcer ni endommager le matériel.',type:'mcq',questions:[{q:'Quel port relie couramment un PC à un réseau local filaire ?',o:['RJ45','HDMI','Audio','VGA'],a:0},{q:'Quel port transporte généralement image et son vers un écran moderne ?',o:['HDMI','RJ45','PS/2','SATA'],a:0},{q:'Quel port convient à une clé USB ?',o:['USB','RJ11','Jack','VGA'],a:0}]},
{id:8,t:'units',title:'Unités de mesure',desc:'Classer les unités de stockage.',visual:'assets/units.svg',concept:'Les capacités numériques s’expriment avec des unités de taille croissante : bit, octet, Ko, Mo, Go, To.',type:'order',items:['bit','octet','Ko','Mo','Go','To']},
{id:9,t:'units',title:'Conversions et comparaison',desc:'Approfondir les relations entre unités.',visual:'assets/units.svg',concept:'Dans les exercices scolaires, on utilise souvent 1 octet = 8 bits et 1 Go ≈ 1024 Mo.',type:'mcq',questions:[{q:'1 octet contient combien de bits ?',o:['2','4','8','16'],a:2},{q:'1024 Mo correspondent approximativement à…',o:['1 Ko','1 Go','1 To','8 Go'],a:1},{q:'Quelle unité est la plus grande ?',o:['Ko','Mo','Go','octet'],a:2},{q:'Pour exprimer la capacité d’un disque moderne, on utilise souvent…',o:['Go ou To','bit seulement','Hz','pixels'],a:0}]},
{id:10,t:'internal',title:'Composants internes',desc:'Identifier visuellement les éléments internes.',visual:'assets/internal.svg',concept:'À l’intérieur de l’unité centrale, la carte mère relie les composants ; le processeur calcule, la RAM travaille temporairement et le SSD stocke.',type:'match',pairs:[['Processeur','Exécute les instructions'],['RAM','Mémoire de travail temporaire'],['SSD','Stocke durablement les fichiers'],['Carte mère','Relie les composants']]},
{id:11,t:'internal',title:'Fonctions des composants',desc:'Associer composant et rôle.',visual:'assets/internal.svg',concept:'Chaque composant interne possède une fonction principale mais travaille avec les autres éléments du système.',type:'mcq',questions:[{q:'Quelle mémoire se vide à l’extinction du PC ?',o:['RAM','SSD','Clé USB','DVD'],a:0},{q:'Quel composant exécute les instructions des programmes ?',o:['Processeur','Ventilateur','Boîtier','Écran'],a:0},{q:'Quel composant relie CPU, RAM et stockage ?',o:['Carte mère','Souris','Haut-parleur','Webcam'],a:0}]},
{id:12,t:'internal',title:'Nommer les composants',desc:'Écrire le nom correct.',visual:'assets/internal.svg',concept:'Utilise le vocabulaire technique précis pour nommer les composants internes.',type:'text',questions:[{q:'Mémoire vive utilisée pendant l’exécution des programmes.',ans:['ram','mémoire ram','memoire ram']},{q:'Composant qui exécute les instructions.',ans:['processeur','cpu']},{q:'Support de stockage rapide sans pièce mécanique.',ans:['ssd','disque ssd']},{q:'Grande carte sur laquelle se branchent les composants.',ans:['carte mère','carte mere']}]},
{id:13,t:'systems',title:'Traitement des données',desc:'Reconstituer le parcours d’une information.',visual:'assets/dataflow.svg',concept:'Un traitement informatique suit souvent un cycle : entrée → traitement → résultat → sortie.',type:'order',items:['Saisie par un périphérique d’entrée','Transmission des données','Traitement par le processeur','Production du résultat','Restitution par un périphérique de sortie']},
{id:14,t:'systems',title:'Système informatique',desc:'Distinguer matériel, logiciel et utilisateur.',visual:'assets/dataflow.svg',concept:'Un système informatique associe des personnes, du matériel et des logiciels afin de traiter de l’information.',type:'classify',cats:['Matériel','Logiciel','Utilisateur'],items:[['Clavier','Matériel'],['Navigateur web','Logiciel'],['Élève','Utilisateur'],['Système d’exploitation','Logiciel'],['Écran','Matériel'],['Enseignant','Utilisateur']]},
{id:15,t:'os',title:'Le bureau',desc:'Se familiariser avec l’environnement graphique.',visual:'assets/desktop.svg',concept:'Le bureau regroupe des icônes, une barre des tâches, un menu d’applications et des zones de notification.',type:'match',pairs:[['Barre des tâches','Montre les applications ouvertes'],['Corbeille','Conserve temporairement des éléments supprimés'],['Icône','Représente un fichier, dossier ou application'],['Menu principal','Donne accès aux applications et réglages']]},
{id:16,t:'os',title:'Éléments du bureau',desc:'Identifier le rôle des éléments d’interface.',visual:'assets/desktop.svg',concept:'Les interfaces graphiques utilisent des fenêtres, dossiers, icônes et menus pour faciliter l’utilisation du système.',type:'mcq',questions:[{q:'Quelle action ouvre souvent un menu contextuel ?',o:['Clic droit','Simple déplacement','Molette seule','Touche espace'],a:0},{q:'Quel élément organise des fichiers ?',o:['Dossier','Fond d’écran','Horloge','Curseur'],a:0},{q:'Où voit-on généralement les applications ouvertes ?',o:['Barre des tâches','BIOS','Corbeille','Câble réseau'],a:0}]},
{id:17,t:'os',title:"Systèmes d’exploitation",desc:'Reconnaître les familles de systèmes.',visual:'assets/os.svg',concept:'Un système d’exploitation gère le matériel et permet d’exécuter les applications.',type:'classify',cats:['Ordinateur','Mobile'],items:[['Windows','Ordinateur'],['GNU/Linux','Ordinateur'],['macOS','Ordinateur'],['Android','Mobile'],['iOS','Mobile']]},
{id:18,t:'os',title:'Système et appareil',desc:'Associer système et type d’appareil.',visual:'assets/os.svg',concept:'Certains systèmes ciblent surtout les ordinateurs de bureau, d’autres les smartphones et tablettes.',type:'match',pairs:[['Windows','PC'],['Android','Smartphone'],['iOS','iPhone / iPad'],['macOS','Mac']]},
{id:19,t:'network',title:'Équipements réseau',desc:'Découvrir les équipements d’un LAN.',visual:'assets/network.svg',concept:'Dans un réseau local, le switch relie les postes, le routeur relie des réseaux et le point d’accès fournit le Wi‑Fi.',type:'match',pairs:[['Switch','Relie plusieurs équipements du LAN'],['Routeur','Relie différents réseaux'],["Point d’accès",'Fournit une connexion sans fil'],['Carte réseau','Permet à un appareil de communiquer']]},
{id:20,t:'network',title:'Équipement LAN',desc:'Choisir l’équipement adapté.',visual:'assets/network.svg',concept:'Le choix d’un équipement dépend de la fonction recherchée : liaison filaire, Wi‑Fi ou interconnexion de réseaux.',type:'mcq',questions:[{q:'Quel équipement relie plusieurs PC dans un LAN filaire ?',o:['Switch','Scanner','Projecteur','SSD'],a:0},{q:'Quel câble est courant pour Ethernet ?',o:['Câble RJ45','HDMI','Jack audio','VGA'],a:0},{q:'Quel équipement diffuse le réseau en Wi‑Fi ?',o:["Point d’accès",'Imprimante','Webcam','Clavier'],a:0}]},
{id:21,t:'network',title:'Nom des équipements LAN',desc:'Écrire le vocabulaire réseau.',visual:'assets/network.svg',concept:'Maîtriser les mots switch, routeur, RJ45, adresse IP et LAN aide à décrire correctement un réseau.',type:'text',questions:[{q:'Équipement qui relie plusieurs postes dans un réseau local.',ans:['switch','commutateur']},{q:'Équipement qui relie plusieurs réseaux.',ans:['routeur','router']},{q:'Connecteur Ethernet courant.',ans:['rj45','rj-45']},{q:'Acronyme anglais de réseau local.',ans:['lan']}]},
{id:22,t:'network',title:'Mots du réseau',desc:'Défi final de vocabulaire réseau.',visual:'assets/network.svg',concept:'Complète les mots à partir des indices. Chaque mot est vérifié indépendamment.',type:'crossword',words:[{w:'SWITCH',clue:'Relie plusieurs postes dans un même réseau local.'},{w:'ROUTEUR',clue:'Relie plusieurs réseaux.'},{w:'WIFI',clue:'Technologie de réseau local sans fil.'},{w:'LAN',clue:'Acronyme anglais de réseau local.'},{w:'IP',clue:'Adresse logique d’un appareil sur un réseau.'}]}
];
const state={done:JSON.parse(localStorage.getItem('infolab_done')||'{}'),scores:JSON.parse(localStorage.getItem('infolab_scores')||'{}'),order:[]};
const view=document.getElementById('view'),nav=document.getElementById('themeNav');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem('infolab_done',JSON.stringify(state.done));localStorage.setItem('infolab_scores',JSON.stringify(state.scores));buildNav()}
function theme(id){return THEMES.find(x=>x.id===id)}
function buildNav(){nav.innerHTML=THEMES.map(t=>`<div class="theme-group"><div class="theme-label">${t.icon} ${t.title}</div>${E.filter(e=>e.t===t.id).map(e=>`<button class="side-ex ${state.done[e.id]?'done':''}" data-ex="${e.id}"><span class="side-num">${state.done[e.id]?'✓':e.id}</span><span>${e.title}</span></button>`).join('')}</div>`).join('');nav.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>openEx(+b.dataset.ex))}
function progress(){const n=Object.keys(state.done).filter(k=>state.done[k]).length;return {n,p:Math.round(n/E.length*100)}}
function home(){history.pushState({home:1},'',location.pathname);const pr=progress();view.innerHTML=`<section class="home-hero"><div><div style="font-weight:800;opacity:.8">APPRENDRE · EXPÉRIMENTER · VÉRIFIER</div><h1>L’atelier du savoir numérique</h1><p>Une série originale de 22 activités interactives pour comprendre l’environnement matériel, les ports, le stockage, les composants internes, le système d’exploitation et les réseaux.</p><div class="stats-row"><span class="stat"><b>22</b> activités</span><span class="stat"><b>${pr.n}</b> terminées</span><span class="stat"><b>${pr.p}%</b> progression</span></div><div class="progressbar" style="margin-top:18px"><span style="width:${pr.p}%"></span></div></div><div class="hero-visual"><img src="assets/computer.svg" alt="Illustration originale d’un poste informatique"></div></section>${THEMES.map(t=>`<section class="home-section"><h2>${t.icon} ${t.title}</h2><div class="cards">${E.filter(e=>e.t===t.id).map(card).join('')}</div></section>`).join('')}`;view.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openEx(+b.dataset.open))}
function card(e){return `<article class="card"><div class="card-top"><span class="num">${e.id}</span>${state.done[e.id]?'<span class="done-tag">✓ Terminé</span>':''}</div><h3>${e.title}</h3><p>${e.desc}</p><button class="start-btn" data-open="${e.id}">${state.done[e.id]?'Revoir':'Démarrer'}</button></article>`}
function openEx(id,push=true){const e=E.find(x=>x.id===id);if(!e)return;if(push)history.pushState({id},'',`#activite-${id}`);document.querySelectorAll('.side-ex').forEach(x=>x.classList.toggle('active',+x.dataset.ex===id));state.order=e.type==='order'?[...e.items].sort(()=>Math.random()-.5):[];view.innerHTML=`<div class="exercise-shell"><div class="breadcrumbs">Accueil › ${theme(e.t).title} › Activité ${e.id}</div><div class="exercise-head"><span class="num">${e.id}</span><div><h1>${e.title}</h1><p>${e.desc}</p></div></div><section class="lesson-card"><div class="concept-box"><b>💡 À retenir :</b> ${e.concept}</div><div class="activity-visual"><img src="${e.visual}" alt="Illustration pédagogique originale"></div><div class="instruction">${instruction(e.type)}</div><div id="activity">${renderActivity(e)}</div><div class="actions"><button class="primary" id="check">✓ Vérifier</button><button class="secondary" id="retry">↻ Recommencer</button></div><div id="feedback" class="feedback"></div></section><div class="pager"><button id="prev">← Précédent</button><button class="home-pager" data-home>⌂ Accueil</button><button id="next">Suivant →</button></div></div>`;bind(e);document.getElementById('prev').onclick=()=>openEx(Math.max(1,id-1));document.getElementById('next').onclick=()=>openEx(Math.min(E.length,id+1));view.querySelector('[data-home]').onclick=home;window.scrollTo({top:0,behavior:'smooth'})}
function instruction(t){return ({mcq:'Choisis la bonne réponse pour chaque question.',match:'Associe chaque élément à la bonne fonction.',classify:'Classe chaque élément dans la catégorie correcte.',order:'Remets les étapes dans le bon ordre avec les flèches.',text:'Écris le terme précis correspondant à chaque définition.',crossword:'Complète les mots du réseau à partir des indices.'})[t]}
function renderActivity(e){if(e.type==='mcq')return e.questions.map((q,i)=>`<div class="question" data-q="${i}"><h3>${i+1}. ${q.q}</h3><div class="options">${q.o.map((o,j)=>`<button class="option" data-a="${j}">${o}</button>`).join('')}</div></div>`).join('');if(e.type==='match')return e.pairs.map((p,i)=>`<div class="field-row"><strong>${p[0]}</strong><select data-i="${i}"><option value="">— Choisir —</option>${shuffle(e.pairs.map(x=>x[1])).map(v=>`<option>${esc(v)}</option>`).join('')}</select></div>`).join('');if(e.type==='classify')return `<div class="sort-grid">${e.items.map((it,i)=>`<div class="sort-card"><strong>${it[0]}</strong><select data-i="${i}"><option value="">— Catégorie —</option>${e.cats.map(c=>`<option>${c}</option>`).join('')}</select></div>`).join('')}</div>`;if(e.type==='order')return `<div class="order-list" id="orderList">${state.order.map((x,i)=>orderRow(x,i)).join('')}</div>`;if(e.type==='text')return e.questions.map((q,i)=>`<div class="field-row"><strong>${i+1}. ${q.q}</strong><input class="text-answer" data-i="${i}" autocomplete="off"></div>`).join('');if(e.type==='crossword')return `<div class="clues">${e.words.map((x,i)=>`<div class="clue"><b>${i+1}.</b> ${x.clue}<div style="display:flex;gap:4px;margin-top:8px">${[...x.w].map((_,j)=>`<input class="cw-letter" data-w="${i}" data-l="${j}" maxlength="1" style="width:31px;height:34px;text-align:center;text-transform:uppercase;border:1px solid #c9d6e5;border-radius:7px;font-weight:900">`).join('')}</div></div>`).join('')}</div>`;return ''}
function orderRow(x,i){return `<div class="order-row"><span class="idx">${i+1}</span><span>${x}</span><span class="order-actions"><button class="tiny" data-up="${i}">↑</button><button class="tiny" data-down="${i}">↓</button></span></div>`}
function bind(e){if(e.type==='mcq')document.querySelectorAll('.question').forEach(q=>q.querySelectorAll('.option').forEach(o=>o.onclick=()=>{q.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));o.classList.add('selected')}));if(e.type==='order')bindOrder();document.getElementById('check').onclick=()=>check(e);document.getElementById('retry').onclick=()=>openEx(e.id,false)}
function bindOrder(){document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{let i=+b.dataset.up;if(i){[state.order[i-1],state.order[i]]=[state.order[i],state.order[i-1]];document.getElementById('orderList').innerHTML=state.order.map((x,j)=>orderRow(x,j)).join('');bindOrder()}});document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>{let i=+b.dataset.down;if(i<state.order.length-1){[state.order[i+1],state.order[i]]=[state.order[i],state.order[i+1]];document.getElementById('orderList').innerHTML=state.order.map((x,j)=>orderRow(x,j)).join('');bindOrder()}})}
function norm(s){return String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function check(e){let score=0,total=0;if(e.type==='mcq'){total=e.questions.length;document.querySelectorAll('.question').forEach((q,i)=>{const s=q.querySelector('.option.selected');if(s&&+s.dataset.a===e.questions[i].a)score++})}if(e.type==='match'){total=e.pairs.length;document.querySelectorAll('#activity select').forEach((s,i)=>{const ok=s.value===e.pairs[i][1];if(ok)score++;s.style.borderColor=ok?'#21b573':'#e84c62'})}if(e.type==='classify'){total=e.items.length;document.querySelectorAll('#activity select').forEach((s,i)=>{const ok=s.value===e.items[i][1];if(ok)score++;s.style.borderColor=ok?'#21b573':'#e84c62'})}if(e.type==='order'){total=e.items.length;score=state.order.filter((x,i)=>x===e.items[i]).length}if(e.type==='text'){total=e.questions.length;document.querySelectorAll('.text-answer').forEach((x,i)=>{const ok=e.questions[i].ans.map(norm).includes(norm(x.value));if(ok)score++;x.style.borderColor=ok?'#21b573':'#e84c62'})}if(e.type==='crossword'){total=e.words.length;e.words.forEach((x,i)=>{let val='';document.querySelectorAll(`[data-w="${i}"]`).forEach(inp=>val+=inp.value);if(norm(val)===norm(x.w))score++})}const fb=document.getElementById('feedback'),pct=Math.round(score/total*100);fb.className='feedback show '+(score===total?'good':'bad');fb.textContent=score===total?`Bravo ! ${score}/${total}. Activité validée.`:`Résultat : ${score}/${total} (${pct}%). Corrige les réponses puis vérifie de nouveau.`;state.scores[e.id]=Math.max(state.scores[e.id]||0,pct);if(score===total)state.done[e.id]=true;save()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function showProgress(){const pr=progress();const rows=E.map(e=>`<div class="score-line"><span>${state.done[e.id]?'✅':'⬜'} ${e.id}. ${e.title}</span><b>${state.scores[e.id]||0}%</b></div>`).join('');view.innerHTML=`<div class="score-panel"><div class="score-big">${pr.p}%</div><h1>Progression de l’élève</h1><p>${pr.n} activité(s) terminée(s) sur ${E.length}. Les résultats restent enregistrés sur cet appareil grâce à localStorage.</p><div class="progressbar"><span style="width:${pr.p}%"></span></div><div class="score-list">${rows}</div><div class="actions"><button class="primary" data-home>Retour à l’accueil</button></div></div>`;view.querySelector('[data-home]').onclick=home}
document.querySelectorAll('[data-home]').forEach(x=>x.onclick=home);document.getElementById('progressBtn').onclick=showProgress;document.getElementById('resetBtn').onclick=()=>{if(confirm('Effacer toute la progression enregistrée sur cet appareil ?')){localStorage.removeItem('infolab_done');localStorage.removeItem('infolab_scores');state.done={};state.scores={};save();home()}};window.onpopstate=e=>{const m=location.hash.match(/activite-(\d+)/);m?openEx(+m[1],false):home()};buildNav();const m=location.hash.match(/activite-(\d+)/);m?openEx(+m[1],false):home();
